// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

let supabase: SupabaseClient<Database> | undefined;
if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
} else {
  console.error('Supabase environment variables are not set');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase };

export function notifySupabaseMissing() {
  alert('Supabase is not configured. Please create a .env file with your Supabase credentials.');
}
