// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuekqnohskepklohhbgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1ZWtxbm9oc2tlcGtsb2hoYmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mzk5MDMsImV4cCI6MjA2NDQxNTkwM30.bVBeoAV7gCaIWZfhBpzUIYwHa3EkO3apzLJC0GWojXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);